Make level 3 in autopark project.
aces47/AutoParkConsole pull request #3
Opened 2021-06-27 15:03 UTC by aces47

Add Engine class.
Add ElectricalEngine class.
Add CombustionEngine class.
Add DieselEngine class.
Add GasolineEngine class.
Modify Vehicle class(add _Engine field, override Equals method).

2021-06-29 09:12 UTC, UNDogMan approved these changes
Approve

2021-06-30 16:41 UTC, PushMeNow approved these changes

2021-06-30 17:01 UTC, kuzmiich requested changes

2021-06-30 17:01 UTC, kuzmiich commented on AutoParkConsole/Program.cs
> +			for (int counter = 0; counter < vehicles.Length - 1; counter++)
This code don`t find all equal vehicles

```suggestion
			for (int counter = 0; counter < vehicles.Length - 1; counter++)
			Add 2 loops, and counter for check 2 repeats
```

2021-06-30 19:09 UTC, kuzmiich commented on AutoParkConsole/Classes/Vehicle.cs
> +			if (obj is Vehicle)
You can use pattern matching
```suggestion
			if (obj is Vehicle)
```

2021-07-01 04:32 UTC, merged