Make level 5 in autopark project.
aces47/AutoParkConsole pull request #5
Opened 2021-06-28 12:21 UTC by aces47

Add Rent class.
Add VehicleComrarer class that implements an Icomprarer<Vehicle> interface.
Add Collections class.
Add types.csv, vehicles.csv, rent.csv files which store information.

2021-07-02 12:49 UTC, PWMaestro commented on AutoParkConsole/Classes/Rent.cs
>  		}
Why are you left empty string between brackets?

2021-07-02 13:02 UTC, aces47 commented on AutoParkConsole/Classes/Rent.cs
>  		}
> Why did you leave empty string between brackets?

Fixed this problem in all files. Thak you.

2021-07-02 13:30 UTC, PWMaestro approved these changes

2021-07-04 18:49 UTC, PushMeNow requested changes

2021-07-04 18:49 UTC, PushMeNow commented on AutoParkConsole/Classes/Collections.cs
> +	internal class Collections
You shouldn't use any libs for csv parsing. Write please yourself parsing and remove TextFieldParser

2021-07-04 19:34 UTC, aces47 commented on AutoParkConsole/Classes/Collections.cs
> +		Vehicle CreateVehicle(string[] csvData)
Fixed

2021-07-04 19:34 UTC, aces47 commented on AutoParkConsole/Classes/Collections.cs
> +	internal class Collections
Fixed

2021-07-04 20:53 UTC, PushMeNow approved these changes

2021-07-04 22:12 UTC, merged