Make level 7 in autopark project.
aces47/AutoParkConsole pull request #7
Opened 2021-06-28 14:12 UTC by aces47

Add MyStack class that implements stack realization.

2021-07-07 14:13 UTC, kuzmiich approved these changes
Normal stack realization. Approve

2021-07-08 18:00 UTC, PushMeNow requested changes

2021-07-08 18:05 UTC, aces47 commented on AutoParkConsole/Classes/MyStack.cs
> +		void Resize()
Fixed.

2021-07-08 18:05 UTC, aces47 commented on AutoParkConsole/Classes/MyStack.cs
> +	class MyStack<T>
Fixed

2021-07-08 18:06 UTC, PushMeNow approved these changes

2021-07-08 18:08 UTC, merged