Make level 8 in autopark project.
aces47/AutoParkConsole pull request #8
Opened 2021-06-28 14:30 UTC by aces47

Add MechanicOrders class thats working with orders.
Add orders.csv file that store information about orders.

2021-06-28 15:54 UTC, dzmitri-litvinov approved these changes

2021-06-28 17:27 UTC, UNDogMan reviewed
Clean your code with [this](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) or [this](https://google.github.io/styleguide/csharp-style.html) code confentions.

2021-06-28 17:27 UTC, UNDogMan commented on AutoParkConsole/Classes/VehicleType.cs
> +		double _TaxCoefficient;
Always set accesses modifiers, even if you now that its necessary.
Also private fields names like _fieldName

2021-06-28 17:27 UTC, UNDogMan commented on AutoParkConsole/Classes/Vehicle.cs
> +		}
U can use doubles CompareTo method for this function.

2021-06-28 17:27 UTC, UNDogMan commented on AutoParkConsole/Classes/Vehicle.cs
> +	}
Put enum in separate file.

2021-06-28 17:27 UTC, UNDogMan commented on AutoParkConsole/Classes/MyStack.cs
> +			}
U can use CopyTo method instead of loop.

2021-06-28 17:27 UTC, UNDogMan commented on AutoParkConsole/Classes/MechanicOrders.cs
> +
Bad naming

2021-06-28 17:29 UTC, UNDogMan requested changes
Check my comment.

2021-07-09 16:22 UTC, PushMeNow requested changes

2021-07-09 16:22 UTC, PushMeNow commented on AutoParkConsole/Program.cs
> +			MechanicOrders orders = new MechanicOrders(pathToCSV + "orders.csv");
I don't have this path in my file system... Use copying files in output dir on compilation and virtual path.

2021-07-09 16:24 UTC, PushMeNow requested changes

2021-07-09 16:24 UTC, PushMeNow commented on AutoParkConsole/Classes/MechanicOrders.cs
> +		private Dictionary<string, int> _orders;
readonly

2021-07-09 16:31 UTC, aces47 commented on AutoParkConsole/Classes/MechanicOrders.cs
> +		private Dictionary<string, int> _orders;
Fixed

2021-07-09 16:32 UTC, aces47 commented on AutoParkConsole/Program.cs
> +			MechanicOrders orders = new MechanicOrders(pathToCSV + "orders.csv");
Fixed

2021-07-09 16:39 UTC, PushMeNow approved these changes

2021-07-16 11:37 UTC, kuzmiich commented on AutoParkConsole/Program.cs
> +            Collections collections =
i 
```suggestion
            var collections =
```

2021-07-16 11:38 UTC, kuzmiich approved these changes
You may add var in Main method
```
Collections collections =  new Collections(pathToCSV + "types.csv", pathToCSV + "vehicles.csv", pathToCSV + "rents.csv");
MyStack<Vehicle> stack = new MyStack<Vehicle>();
```

2021-07-16 11:39 UTC, kuzmiich approved these changes

2021-07-16 11:41 UTC, merged